Config:
  path: /scr2/haipeng/SWIT-1.1/01_fwi/
  job_type: fwi
  cpu_max_num: 48
  mpi_num: 40
  fig_aspect: 1.0

Model:
  dt: 0.002
  dx: 25
  nt: 2001
  nx: 481
  nz: 141
  pml: 40
  acquisition_type: land
  vp_true: /homes/sep/haipeng/develop/SWIT-1.0/examples-dev/case-01-Marmousi2/acquisition/vp_true.npy
  rho_true: /homes/sep/haipeng/develop/SWIT-1.0/examples-dev/case-01-Marmousi2/acquisition/rho_true.npy

Receiver:
  comp: p
  coord_file: /homes/sep/haipeng/develop/SWIT-1.0/examples-dev/case-01-Marmousi2/acquisition/rec_coord.npz

Source:
  amp0: 1.0
  f0: 5.0
  type: ricker
  coord_file: /homes/sep/haipeng/develop/SWIT-1.0/examples-dev/case-01-Marmousi2/acquisition/src_coord.npy
  wavelet_file: /homes/sep/haipeng/develop/SWIT-1.0/examples-dev/case-01-Marmousi2/acquisition/wavelets.npy

Optimizer:
  vp_init: /homes/sep/haipeng/develop/SWIT-1.0/examples-dev/case-01-Marmousi2/acquisition/vp_init.npy
  rho_init: /homes/sep/haipeng/develop/SWIT-1.0/examples-dev/case-01-Marmousi2/acquisition/rho_init.npy
  misfit_type: waveform
  method: LBFGS
  niter_max: 20
  bound: false
  vp_max: 5000
  vp_min: 1000
  grad_smooth_size: 0
  update_vpmax: 50
  grad_mask: null
  debug: false

Preprocessor:
  filter_data: none
  filter_high: 10.0
  filter_low: 5.0
  mute_near_offset: true
  mute_near_distance: 500
  mute_far_offset: true
  mute_far_distance: 8000
  mute_late_arrival: true
  mute_late_size: 0.5
  normalize_data: false
