###############################################################################
# SWIT v1.1: Seismic Waveform Inversion Toolbox
#
# Description: This is a configuration file in YAML format for SWIT-1.1.
#              It is used to configure the workflow of SWIT-1.1.
#   Note: 
#              Workflow: define the overall workflow of SWIT-1.1. 
#              System: define working directory and system parameters
#              Model: define the model used in wavefield simulation
#              Receiver: define the receiver locations and components
#              Source: define the source locations and wavelet
#              Optimizer: define the optimizer in FWI (only effective for FWI job)
#              Preprocessor: define the data preprocessor (effective for both FWI and RTM jobs)
#   Any illegal parameters will cause SWIT-1.1 to exit with error explanation.
# 
###############################################################################

# Define the overall workflow of SWIT-1.1
Workflow:         
  job_workflow:           # job workflow: FORWARD, FWI, RTM, or any combination of them 
      - FORWARD
      - FWI
  simu_tag: obs           # only effective for FORWARD job, simulation tag such as obs, syn, or any other tag you want to use 
  save_sanp: false        # only effective for FORWARD job, save snapshot or not

# Define the system parameters
System:
  path: /scr2/haipeng/SWIT-1.1/07-WT-tomo/stage2/
  mpi_cpu_num: 21
  max_cpu_num: 40
  fig_aspect:  1.0

# Define the model size and model files
Model:
  nx: 481
  nz: 121
  dx: 25
  nt: 4001
  dt: 0.002
  pml: 40
  vp_file:  /homes/sep/haipeng/develop/SWIT-1.0/dev/examples-dev/07-WT-tomo/acquisition/vp_true.npy
  rho_file: /homes/sep/haipeng/develop/SWIT-1.0/dev/examples-dev/07-WT-tomo/acquisition/rho_true.npy

# Define the receiver coordinates and components
Receiver:
  rec_comp: vz    # for the land acquisition, oftentime data in the vz (vertical velocity) component is available
  rec_coord_file: /homes/sep/haipeng/develop/SWIT-1.0/dev/examples-dev/07-WT-tomo/acquisition/rec_coord.npz

# Define the source coordinates and wavelet
Source:
  amp0: 1.0
  f0: 5.0
  src_type: file
  src_coord_file: /homes/sep/haipeng/develop/SWIT-1.0/dev/examples-dev/07-WT-tomo/acquisition/src_coord.npy
  wavelet_file:   /homes/sep/haipeng/develop/SWIT-1.0/dev/examples-dev/07-WT-tomo/acquisition/wavelets.npy

# Define the optimizer in FWI
Optimizer:
  vp_init_file:   /homes/sep/haipeng/develop/SWIT-1.0/dev/examples-dev/07-WT-tomo/acquisition/vp_tomo.npy
  rho_init_file:  /homes/sep/haipeng/develop/SWIT-1.0/dev/examples-dev/07-WT-tomo/acquisition/rho_tomo.npy
  grad_mask_file:    # if empty, default gradient damping masking is applied
  misfit_type: globalcorrelation
  method: CG
  niter_max: 20
  bound: true
  vp_min: 1000
  vp_max: 5000
  grad_smooth_size: 0
  update_vpmax: 50
  debug: false

# Define the data preprocessor for FWI and RTM
Preprocessor:
  filer: none
  filter_high: 10.0
  filter_low: 5.0
  mute_near_offset: false
  mute_near_distance: 500
  mute_far_offset: false
  mute_far_distance: 8000
  mute_late_arrival: false
  mute_late_size: 0.30
  normalize_data: false
